version: "3.9"
services:
  api:
    build: ./back
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - dev
    volumes:
      - ./back:/workspace:cached
      - ./scripts:/scripts

  web:
    build: ./front
    ports:
      - 3000:3000
    volumes:
      - ./front:/app
    depends_on:
      - api
    networks:
      - dev

  db:
    image: postgres:15
    ports:
      - 5432:5432
    env_file:
      - .env.docker
    networks:
      - dev

networks:
  dev:
    driver: bridge
