FROM node:20-alpine

WORKDIR /app

RUN npm config set legacy-peer-deps true \
    && npm config set strict-peer-deps false

COPY package*.json ./

ENV NODE_ENV=development

RUN npm install

COPY . .

CMD [ "npm", "start" ]